---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: querier
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: querier
